-- SQL script to create the `login` database and `auth_tokens` table

CREATE DATABASE login;

USE login;

CREATE TABLE auth_tokens (
    id INT AUTO_INCREMENT PRIMARY KEY,
    login_key VARCHAR(32) NOT NULL,
    user_id INT NOT NULL
);

-- Example indexes for better performance
CREATE INDEX idx_login_key ON auth_tokens(login_key);
CREATE INDEX idx_user_id ON auth_tokens(user_id);

-- Description of fields:
-- id: Auto-incrementing unique identifier for each record.
-- login_key: A unique authorization token generated by the system.
-- user_id: The ID of the user to whom the token belongs.
